---

- name: "create the iptables rules directory"
  file:
    path: "/etc/iptables"
    owner: "root"
    group: "root"
    mode: "0700"
    state: "directory"

- name: "save IPv4 rules"
  template:
    src: "iptables.rules.j2"
    dest: "/etc/iptables/iptables.rules"
    owner: "root"
    group: "root"
    mode: "0400"

- name: "save IPv6 rules"
  template:
    src: "ip6tables.rules.j2"
    dest: "/etc/iptables/ip6tables.rules"
    owner: "root"
    group: "root"
    mode: "0400"

- name: "start iptables service"
  service:
    name: "{{ item }}"
    enabled: yes
    state: reloaded
  with_items:
    - "iptables"
    - "ip6tables"
