---

- name: "reload iptables services"
  listen: "reload iptables-services"
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items: "{{ iptables_services }}"

- name: "persist ipsets"
  listen: "persist ipsets"
  shell:
    cmd: "ipset save > /etc/ipset.conf"
